rules = {
    r"(how to register|how can i register|steps to register|registering process)": "The registration process is on the SIS website.",
    r"(when (can|is) .*register|registration date|registration opens)": "Registration opens on January 5.",
    r"(credit|credits|credit hours)": "Each course is worth 3 credit hours.",
    r"(deadline|add/drop)": "The add/drop deadline is January 18.",
    r"(advisor|advising)": "You must meet your academic advisor each semester.",
    r"(graduation|graduate)": "Graduation requires at least 120 credit hours.",
    r"(schedule|class time)": "You can see your schedule on the SIS website",
    r"(library|books)": "Library hours are 8AM–10PM every day.",
    r"(fees|payment|tuition)": "Tuition fees must be paid before week two.",
    r"(Exam | Midterm | Final)": "Final exams are offered at the time of registration, but the midterm is agreed upon by the professor with the students.",
    r"(scholarship | financial aid)": "Scholarships require GPA above 90",    
    r"(wifi|internet)": "Campus WIFI password: your student ID.",
    r"(campus map|map|location)": "You can find the map at the reception building.",
    r"(Parking|Car|Vehicle)": "There are many parking spaces at the university",  
    r"(cafeteria|food)": "Cafeteria is open from 9AM–8PM.",
    r"(housing|dorm|accommodation)": "University housing applications open in August.",
    r"(ID card|student card)": "Replacement ID costs 10BH.",
    r"(transcript|grades)": "You can request transcripts from the registrar office or from SIS website.",
    r"(portal|login)": "Use your student ID to access the portal.",
    r"(password reset|forgot password)": "Reset password via IT helpdesk portal.",
    r"(orientation|new student)": "Orientation week starts September 1.",
    r"(office hours|faculty hours)": "Office hours vary per instructor and are posted online.",
}
